activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 4
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 5.0
dataset: MD17
dataset_arg: aspirin
dataset_root: ./md17_datasets/
derivative: true
distance_influence: both
distributed_backend: ddp
early_stopping_patience: 600
ema_alpha_dy: 1.0
ema_alpha_y: 0.05
embed_files: null
embedding_dimension: 256
energy_files: null
energy_weight: 0.01
force_files: null
force_weight: 0.99
inference_batch_size: 64
load_model: null
log_dir: ./logs
lr: 0.0004
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 30
lr_warmup_steps: 1000
max_num_neighbors: 32
max_z: 100
model: QuinNet
neighbor_embedding: true
ngpus: -1
num_epochs: 1000000
num_heads: 8
num_layers: 5
num_nodes: 1
num_rbf: 32
num_workers: 6
order: 2
output_model: Scalar
precision: 32
prior_model: Atomref
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 1
splits: null
standardize: true
test_interval: 1000
test_size: null
train_size: 950
trainable_rbf: false
val_size: 50
weight_decay: 0.0
